title: Xiaotong Liu
affiliation: George Washington University
email: liuxiaotong2017@gwu.edu
google_scholar: https://scholar.google.com/citations?hl=en&user=xXvtWJMAAAAJ
github_link: https://github.com/LiuXiaotong96
linkedin: https://www.linkedin.com/in/xiaotong-liu-679151226/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: testtest
canonical: https://minimal-light.yyliu.net/
# remote_theme: yaoyao-liu/minimal-light
remote_theme: yaoyao-liu/minimal-light
